package:
  name: gcc-libs
  version: 7.2.0
  description: fjdklfjad
  license: []
  skip_extract: true

  source:
    - https://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.xz
  
  prepare:
    - tar -Jxf gcc-7.2.0.tar.xz -C ${builddir}

  build:
    - echo `pwd`
    - ls
